"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv


# ==========================
# BASE DIR / ENV
# ==========================

BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables del archivo .env en local
load_dotenv(BASE_DIR / ".env")


# ==========================
# HELPERS
# ==========================

def get_bool_env(name, default=False):
    """
    Convierte variables de entorno tipo True/False a booleanos.
    """
    value = os.getenv(name)

    if value is None:
        return default

    return value.lower() in ["true", "1", "yes", "y"]


def get_list_env(name, default=""):
    """
    Convierte variables separadas por coma en lista.
    Ejemplo:
    ALLOWED_HOSTS=127.0.0.1,localhost,resergo.es
    """
    value = os.getenv(name, default)

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]


# ==========================
# SECURITY
# ==========================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-pbtntlun8!3t*i%v2t-9-_*z(93p9$x38(&voy!4ep4i9_n5l7"
)

DEBUG = get_bool_env("DEBUG", False)

ALLOWED_HOSTS = get_list_env(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
)

# En desarrollo puedes entrar por 127.0.0.1.
# En producción añadiremos aquí tu dominio y la URL de Render desde variables.
CSRF_TRUSTED_ORIGINS = get_list_env(
    "CSRF_TRUSTED_ORIGINS",
    ""
)


# ==========================
# APPLICATION DEFINITION
# ==========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'businesses',
    'employees',
    'services_app',
    'bookings',
    'customers',
    'api',
    'schedules',
    'public_booking',
    'dashboard',
    'automations',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # WhiteNoise sirve archivos estáticos en producción.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    # Demo solo lectura:
    # el usuario demo puede ver el panel, pero no guardar cambios.
    'accounts.middleware.DemoReadOnlyMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# ==========================
# DATABASE
# ==========================

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Producción: PostgreSQL en Render
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Local: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ==========================
# PASSWORD VALIDATION
# ==========================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==========================
# INTERNATIONALIZATION
# ==========================

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# ==========================
# STATIC FILES
# ==========================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise + Django 5
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ==========================
# MEDIA
# ==========================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==========================
# DEFAULT PRIMARY KEY
# ==========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================
# API
# ==========================

API_SECRET_KEY = os.getenv(
    "API_SECRET_KEY",
    "mi_clave_super_secreta_123"
)


# ==========================
# LOGIN / LOGOUT
# ==========================

LOGIN_REDIRECT_URL = "/dashboard/"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"


# ==========================
# EMAILS - BREVO SMTP
# ==========================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp-relay.brevo.com"
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "ReserGo <reservas.resergo@gmail.com>"
)

EMAIL_TIMEOUT = 5


# ==========================
# CSRF
# ==========================

CSRF_FAILURE_VIEW = "accounts.views.custom_csrf_failure"


# ==========================
# PRODUCTION SECURITY
# ==========================
# Estas opciones solo se activan cuando DEBUG=False.
# En local se quedan apagadas para no dar problemas con http://127.0.0.1:8000

if not DEBUG:
    SECURE_SSL_REDIRECT = get_bool_env("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS: le dice al navegador que siempre use HTTPS con este dominio.
    # Empezamos con un valor bajo (1 día) y se puede subir más adelante
    # una vez confirmado que todo funciona bien por HTTPS.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "86400"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = get_bool_env(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", False
    )
    SECURE_HSTS_PRELOAD = get_bool_env("SECURE_HSTS_PRELOAD", False)
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False