# -*- coding: utf-8 -*-
"""
Created on Wed Jul 15 18:12:59 2026

@author: PRL
"""

# Generated by Django 5.2.13 on 2026-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_blockedslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='end_time_morning',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='start_time_morning',
            field=models.TimeField(blank=True, null=True),
        ),
    ]