# Generated by Django 5.2.13 on 2026-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='theme',
            field=models.CharField(choices=[('classic', 'Clásico'), ('modern', 'Moderno'), ('beauty', 'Belleza')], default='classic', max_length=30),
        ),
    ]
