# Generated by Django 5.2.13 on 2026-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_past_bookings',
            field=models.BooleanField(default=False, verbose_name='Permitir reservas en fechas pasadas'),
        ),
        migrations.AddField(
            model_name='business',
            name='max_advance_days',
            field=models.PositiveIntegerField(default=31, verbose_name='Días máximos de antelación'),
        ),
        migrations.AddField(
            model_name='business',
            name='min_advance_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='Horas mínimas de antelación'),
        ),
    ]
