# -*- coding: utf-8 -*-
"""
Created on Sun Jul 12 18:14:58 2026

@author: PRL
"""

# Generated by Django 5.2.13 on 2026-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_alter_business_options_alter_business_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slot_interval_minutes',
            field=models.PositiveIntegerField(choices=[(5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos'), (20, '20 minutos'), (30, '30 minutos'), (60, '60 minutos')], default=15, help_text='Cada cuántos minutos se ofrecen horas de inicio a los clientes (por ejemplo, cada 15 minutos: 10:00, 10:15, 10:30...). Un intervalo más pequeño aprovecha mejor la agenda con servicios de duración poco redonda, pero muestra más opciones.', verbose_name='Intervalo entre horas de reserva'),
        ),
    ]