# -*- coding: utf-8 -*-
"""
Created on Wed Jul 15 19:00:45 2026

@author: PRL
"""

# Generated by Django 5.2.13 on 2026-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_slot_interval_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='theme',
            field=models.CharField(choices=[('classic', 'Clásico'), ('modern', 'Moderno'), ('beauty', 'Belleza'), ('bold', 'Atrevido'), ('nature', 'Natural'), ('elegant', 'Elegante')], default='classic', max_length=30, verbose_name='Tema visual'),
        ),
    ]