# Generated by Django 5.2.13 on 2026-05-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0005_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_customer_email', models.BooleanField(default=True, verbose_name='Enviar email al cliente')),
                ('send_business_email', models.BooleanField(default=True, verbose_name='Enviar email al negocio')),
                ('customer_subject', models.CharField(default='Reserva confirmada en {business_name}', max_length=200, verbose_name='Asunto email cliente')),
                ('customer_body', models.TextField(default='Hola {customer_name},\n\nTu reserva ha sido confirmada correctamente.\n\nDetalles de la reserva:\n\nNegocio: {business_name}\nServicio: {service_name}\nProfesional: {employee_name}\nFecha: {booking_date}\nHora: {start_time}\nFin estimado: {end_time}\n\nGracias por reservar con nosotros.\n\nUn saludo,\n{business_name}\n', verbose_name='Mensaje email cliente')),
                ('business_subject', models.CharField(default='Nueva reserva recibida - {business_name}', max_length=200, verbose_name='Asunto email negocio')),
                ('business_body', models.TextField(default='Hola {business_name},\n\nHas recibido una nueva reserva.\n\nDetalles de la reserva:\n\nCliente: {customer_name}\nTeléfono: {customer_phone}\nEmail: {customer_email}\n\nServicio: {service_name}\nProfesional: {employee_name}\nFecha: {booking_date}\nHora: {start_time}\nFin estimado: {end_time}\n\nEstado: {booking_status}\n\nPuedes verla desde tu panel de reservas.\n\nUn saludo,\nSistema de reservas\n', verbose_name='Mensaje email negocio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_template', to='businesses.business')),
            ],
        ),
    ]
