# -*- coding: utf-8 -*-
"""
Created on Sun Jul 12 17:27:49 2026

@author: PRL
"""

# Generated by Django 5.2.13 on 2026-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancel_token'),
        ('businesses', '0006_alter_business_options_alter_business_created_at_and_more'),
        ('customers', '0001_initial'),
        ('employees', '0002_employeeservice'),
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('business', 'employee', 'booking_date', 'start_time'), name='unique_confirmed_booking_slot'),
        ),
    ]