# -*- coding: utf-8 -*-
"""
Created on Wed Aug 26 12:14:49 2026

@author: PRL
"""

# Generated by Django 5.2.13 on 2026-08-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_unique_confirmed_booking_slot'),
        ('customers', '0001_initial'),
        ('employees', '0002_employeeservice'),
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services_app.service'),
        ),
    ]