# Generated by Django 5.2.13 on 2026-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='end_time',
            new_name='end_time_morning',
        ),
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='start_time',
            new_name='start_time_morning',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='end_time_afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='start_time_afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
