# Generated by Django 5.2.13 on 2026-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_blockedslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='end_time_morning',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='start_time_morning',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
